name: Run Tests and Generate Coverage Report

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        shell: /usr/bin/bash --login
        working-directory: ${{ github.workspace }}
        path: ${{ github.workspace }}/.github/actions/
        shell: /usr/bin/bash --login {0}
    env:
      PYTHON_VERSION: "3.9"
      NODE_VERSION: "16.x"

    steps:
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests with coverage
        run: coverage run --source='.' manage.py test

      - name: Generate coverage report
        run: coverage report